### ISSUE TITLE
프론트엔드 개발

### ISSUE THREAD

**Issue by secureWKkim** [97zPaleBlueDot/Client#1]
## 어떤 기능인가요?
> 웹 사이트 제작 (https://palebluedot97z.retool.com/)

## ✅ Task List
- [x] 메인 페이지(검색창 페이지) 제작
- [x] 최저가 레시피 검색 결과 (정확히 일치하는 메뉴) 페이지 제작
- [x] 예외/에러 페이지 제작
- [ ] (challenge) 유사 검색 결과 (비슷한 메뉴) 페이지 제작
- [ ] (challenge) 대체제 선택 화면 개발
- [ ] (challenge) 대체제 사용하는 경우마다 별개의 가격 총액 보여주기
---

### 💡 고려사항
- 1~2주 내로 끝..이 목표였으나, 웹&앱 하이브리드형 디자인이 안되고 각각 따로 디자인 해야 함.
- 1~2일에 페이지 1개씩 디자인한다고 생각해야 할 듯

<br>

> #### Reference
> NULL
> - [title](link)

**Comment by secureWKkim** [comment]
- [x] REST API 사용법
- [x] 응답 JSON 속 value 불러와 사용하기
       - GPT에서 하란 대로 하면 "Wrapping code in {{ }} is not supported here." 라는 에러가 뜸. 별도의 방법을 다시 봐야함
- [x] 원하는 이미지를 유튜브 영상 뒤편에 데코레이션으로 '겹치게' 놓는 법  // 또 안됨
- [x] 유튭 영상 임베딩
- [x] 쿠팡 상품 사진 / 정보 임베딩
- [x] Stack 사용해 fancy한 재료 list view 구현법. 안되면 걍 슬라이딩 바라도...
- [ ] 컴포넌트 크기 조정법
- [x] 컴포넌트 위치 조정 더 섬세하게 하는 법
- [x] List View 세로로 스크롤해서 보는 법
- [x] (option) JS 에러 고치기

**Comment by secureWKkim** [comment]
검색창 메인 홈에 ListView 로 가장 많이 검색한 레시피들의 최저가를 미리 보여주는 idea.
